version: '2'
services:
    todolistapp-app:
        image: todolistapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://todolistapp-mysql:3306/todolistapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://todolistapp-elasticsearch:9200
        ports:
            - 8080:8080
    todolistapp-mysql:
        extends:
            file: mysql.yml
            service: todolistapp-mysql
    todolistapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: todolistapp-elasticsearch
